name: hospy
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  flutter_gen: ^5.7.0
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  logger: ^2.4.0
  firebase_auth: ^5.2.0
  intl_phone_number_field: ^0.2.0
  flutter_otp_text_field: ^1.2.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  cloud_firestore: ^5.3.0
  stylish_bottom_bar: ^1.1.0
  animated_text_kit: ^4.2.2
  page_transition: ^2.1.0
  url_launcher: ^6.3.0
  colorful_safe_area: ^1.0.0
  shimmer: ^3.0.0
  animated_toggle_switch: ^0.8.3
  flutter_toggle_tab: ^1.4.1
  toggle_switch: ^2.3.0
  flutter_toggle_button: ^0.0.3
  styled_divider: ^1.0.5
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.0 
  flutter_gen_runner: ^5.7.0 
flutter:
  uses-material-design: true

  assets:
    - assets/png/ 
    - assets/svg/
    - assets/jpg/
  
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/SF-Pro-Display-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/SF-Pro-Display-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/SF-Pro-Display-BlackItalic.otf
          weight: 900
          style: italic

    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Text-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/SF-Pro-Text-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/SF-Pro-Text-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/SF-Pro-Text-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/SF-Pro-Text-HeavyItalic.otf
          weight: 800
          style: italic

  # flutter_gen is not a direct child of flutter
flutter_gen:
  outputs:
    font:
      - asset: assets/fonts
